require 'asciidoctor'
require 'rake'

source = Rake::FileList.new("**/*.adoc") do |fl|
    fl.exclude("~*")
end

task :default => :build

task :build, :paths do |t, args|
    args.with_defaults(:paths => source)
    args.paths.each { |f|
        Asciidoctor.convert_file f, safe: 'unsafe'
    }
end
